### ISSUE TITLE
Add explanation, if absolute or relative path for filecopier

### ISSUE THREAD

**Issue by schiggi** [butopea/vue-storefront-opencart-vsbridge#1]
Would make sense to add a little note in readme, how the path has to be constructed. Like in https://github.com/sasedev/composer-plugin-filecopier (Installation/Usage Step 2) to make it clear.

**Comment by themreza** [comment]
Was there an issue with the composer vendor path? The `source` path shouldn't be changed in most cases as it assumes a vendor folder present next to composer.json.

The `destination` path, however, does need to be adjusted depending on the name of the OpenCart code folder (in vanilla OpenCart it's `upload`, in other cases perhaps `public`, etc.). This is already indicated in the readme.

**Comment by themreza** [comment]
Fixed.
